### ISSUE TITLE
Plans for future

### ISSUE THREAD

**Issue by dom96** [stisa/nwasm#1]
Just wondering what your plans are with integrating this into upstream. 

This repo seems to be a fork of the Nim repo, but it modifies the readme which will probably be problematic to deal with in the future.

Have you considered following [nlvm's](https://github.com/arnetheduck/nlvm) approach? Doing it this way might make contributing easier to this effort as it will be easier to see where the webasm code gen is.

**Comment by stisa** [comment]
My original approach was similar to nlvm, you can see it on https://github.com/stisa/nwasm/tree/beforesimplification , but I changed it due to alehander42 suggestion of simplifying the build process. I quite like being able to just clone and run koch.

You are right about the readme, I didn't think about it. I could probably set a dummy branch as main with my readme and link to a separate fork branch which has the code? This would have the benefit of allowing to compare the code via github pull request interface, 

As for contributing, all relevant files are either in a `wasm` folder or have wasm in the name (`wasmgen wasmutil wasmsys`...) , the changes to other files are just on or two lines to make nim recognize wasm as a target. The actual wasm translation is only in wasmgen, and I substitute wasmsys.nim to system.nim so I can try out changes incrementally, before implementing the whole thing.

( Honestly, I didn't even think about integrating with upstream, I just wanted to see how far I could go compiling without external libs. But if there's interest, I'm open to restructuring the project )

**Comment by dom96** [comment]
The structure of the project depends on whether you wish to integrate it with upstream or not. If you do then the current structure is better, if not then it's best to have a separate tool :)

But yeah, some info in the readme about the files which the wasmgen lives in would be great. Otherwise just keep going and I hope others will help out and we can get this into upstream eventually.
